spring.application.name=FoodFly

spring.datasource.url=jdbc:mysql://mysql-siddhi.alwaysdata.net:3306/siddhi_fooffly_db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=siddhi
spring.datasource.password=Foodfly@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


server.port=${PORT:8080}
server.address=0.0.0.0




spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.secret.id=${RAZORPAY_SECRET_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000



spring.security.user.name=admin
spring.security.user.password=a69b7fe0-5b65-44bb-b378-aa061e6371c6
